### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by rotaz-bots** [locaweb/ftp-deploy#1]
Ao automatizar o deploy do meu sites estou me deparando com o seguinte erro:

`Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/`

**Comment by rhruiz** [comment]
O pedaço que usa o node12 no pipeline deve ser o `actions/checkout@v2`, atualiza pro `actions/checkout@v3`

**Comment by rhruiz** [comment]
Arrumado com [fab347d](https://github.com/locaweb/ftp-deploy/commit/fab347d8fa73c7e4ce2dac220dc49727e1c4126c)
